### ISSUE TITLE
IndexError: index 0 is out of bounds for dimension 0 with size 0

### ISSUE THREAD

**Issue by Zio-21** [SysCV/ovtrack#19]
I followed the “OVTRACK_GEN.md” to generate the images. When I run the command 
`tools/run_ovtrack_generation.sh $GPUs $RESULT_FOLDER_NAME`
it returns an error:
Traceback (most recent call last):
  File "/data/anaconda/envs/diffusers_clean/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data/anaconda/envs/diffusers_clean/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data/public/sdzh/OVT/ovtrack-main/diffusers_clean/ovtrack_diffusion_generation.py", line 464, in <module>
    main()
  File "/data/public/sdzh/OVT/ovtrack-main/diffusers_clean/ovtrack_diffusion_generation.py", line 453, in main
    process_image(imid, args, coco_obj, ovtrack_gen_pipe, out_dataset,
  File "/data/public/sdzh/OVT/ovtrack-main/diffusers_clean/ovtrack_diffusion_generation.py", line 301, in process_image
    g_img = generate_transformed_image(ovtrack_gen_pipe, prompt, init_img, mask_img, args.delta, crop_size, ori_size, guidance_scale)
  File "/data/public/sdzh/OVT/ovtrack-main/diffusers_clean/ovtrack_diffusion_generation.py", line 331, in generate_transformed_image
    g_img = ovtrack_gen_pipe(prompt=prompt,
  File "/data/anaconda/envs/diffusers_clean/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/data/public/sdzh/OVT/ovtrack-main/diffusers_clean/pipelines/stable_diffusion/pipeline_ovtrack_image_generation.py", line 396, in __call__
    t_start = ((times == timesteps[0].cpu()).nonzero(as_tuple=True)[0])[0]
IndexError: index 0 is out of bounds for dimension 0 with size 0

**Comment by Zio-21** [comment]
In addition, I didn't find the file './data/lvis/train_imgs.hdf5' so I rm the command '--h5_img ./data/lvis/train_imgs.hdf5 \' in tools/run_ovtrack_generation.sh. Is this necessary?

**Comment by Zio-21** [comment]
In addition, I didn't find the file './data/lvis/train_imgs.hdf5' so I rm the command '--h5_img ./data/lvis/train_imgs.hdf5 ' in tools/run_ovtrack_generation.sh. Is this file necessary?

**Comment by Zio-21** [comment]
I recreate the envs and it runs : )
